language: php

branches:
  only:
    - master
    - 0.1.x

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - php -r "eval('?>'.file_get_contents('https://getcomposer.org/installer'));"
  - php composer.phar install --dev --no-interaction --prefer-dist

script:
    - mkdir -p build/logs
    - composer test -- --coverage-text

after_script:
 - php vendor/bin/coveralls -v

notifications:
  email:
    - mudi@renegare.com

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true
